### ISSUE TITLE
スケジュール＋ふりかえり

### ISSUE THREAD

**Issue by shimoju** [shimoju/rails-tutorial#5]
## スケジュール
- 〜7/15 25営業日
- でも職種共通の講義やいろいろが挟まる
- 23営業日くらいでしょうか
- 単純計算で2日で1章だが、もちろん後半になるほど難しい

---
- （目次： #2）
- [x] 1. From zero to deploy：ゼロからデプロイまで [6/13-6/14] #6
- [x] 2. A toy app：おもちゃアプリ [6/14-6/15] #7
- [x] 3. Mostly static pages：たいていは静的ページ [6/15-6/17] #8 #10 
- [x] 4. Rails-flavored Ruby：Rails風味のRuby [6/17] #11 
- [x] 5. Filling in the layout：レイアウトを満たす [6/20] #12 #14 
- [x] 6. Modeling users：usersをモデリングする [6/21-6/23] #17 #19 
- [x] 7. Sign up：サインアップする [6/23-6/27] #20 #21 
- [x] 8. Log in, log out：ログイン・ログアウトする [6/27-7/1] #22 #23  
- [x] 9. Updating, showing, and deleting users：usersを更新、表示、削除する [7/1-7/5] #24 #25 
- [x] 10. Account activation and password reset：アカウント有効化とパスワードリセット [7/5-7/11] #26  
- [x] 11. User microposts：ユーザーのmicroposts [7/11-7/13] #32 
- [ ] 12. Following users：ユーザーをフォローする [7/13-7/15] #39 
## 目標→そのために何をするか
- 期日までにすべての章を終わらせる
  - そのために→各章の見積もりを立てる
- やっただけにしない
  - そのために→記録を確実に残す
  - 読解メモ+エクササイズのPR
- 英語を読み飛ばさない
  - そのために→どうしよう
  - 1章を読んでみた結果、英語全部読んでると到底終わらなさそう
  - なんとなくでいいので英語に「慣れる」を目標にする
  - そのために→全部は無理だが、必要と思う部分はなんとなくにせず読み込む

**Comment by shimoju** [comment]
単純計算で2日で1章だが、もちろん後半になるほど難しい

1. From zero to deploy：ゼロからデプロイまで①
2. A toy app：おもちゃアプリ
3. Mostly static pages：たいていは静的ページ
4. Rails-flavored Ruby：Rails風味のRuby
5. Filling in the layout：レイアウトを満たす
6. Modeling users：usersをモデリングする
7. Sign up：サインアップする
8. Log in, log out：ログイン・ログアウトする
9. Updating, showing, and deleting users：usersを更新、表示、削除する
10. Account activation and password reset：アカウント有効化とパスワードリセット
11. User microposts：ユーザーのmicroposts
12. Following users：ユーザーをフォローする

**Comment by shimoju** [comment]
## 毎日のふりかえり
- 今日やったこと
- 明日やること
- スケジュール
  - 進んでいる・遅れている

### KPT

### その他

**Comment by shimoju** [comment]
またくが#devのgithubインテグレーションを爆破したかも事件

**Comment by shimoju** [comment]
## 毎日のふりかえり 6/14
- 今日やったこと
  - Ch1 #6 終了、Ch2 #7 の途中で終わった
- 明日やること
  - 引き続きCh2を進める
- スケジュール
  - Ch1の終了に2日かかった
    - ただ、1日目は目標設定や進め方を考えていたのと、今日は物理ロック解除できないトラブルがあった
    - 実質的な時間としては1日程度だが、差し込み作業やトラブルがあると厳しい
- KPT
  - K：Railsは触ったことがあるので、わかるところはさっと読んでスピードアップ
  - P：休憩時間管理、集中力
    - （今後…後半の章で英語がきつくなりそう）
  - T：タイマー導入（ポモドーロもよさそう）、イヤホンしてみる

**Comment by shimoju** [comment]
トイレ+Yoursに行くと強制的に10分近く休憩が取れて軽い運動（階段上り下り）もできてよい

**Comment by shimoju** [comment]
午前：1時間ごと休憩、タイマーは使わずきりのいいとこまででやった
午後はタイマーとイヤホンを試す

**Comment by shimoju** [comment]
またくのChapter3のレビューを依頼されたが、自分はまだch3のエクササイズに入ってないので、(コード自体はよさそうな感じはするけど)どう実装されていれば正しいのかがわからない、レビューができない、という問題が発生

みんなで相談したところ、じょうさんから「実際の業務も自分が開発してる機能は自分しか知らないので同じ問題が起こる」と言われ、
じゃあどうする？ということで、「このような機能を実装したけど、ここが正しいか見てほしい」とか、「ここを重点的に見てほしい」というレビューポイントをレビュアーに伝えないといけない、という話になった
また、コミットの分割単位やコミットコメントもレビューには重要な情報になるので、チュートリアルだからと適当にやらず、わかりやすいようにするのも重要という話をした

**Comment by shimoju** [comment]
レビューの難しさその2
https://github.com/Asuforce/rails_tutorial/pull/7

Travis CIの設定が正しくできているか、というレビューだったが、
CIもpassしてるし一見問題なさそうに見えてLGTMしたら、
postgresの設定に変な文字が入り込んでいて正しく設定できていなかった。
完全に見落としていた

https://github.com/Asuforce/rails_tutorial/pull/9

> まだ db/ 以下に何も無くて、Travisのログの db:create や db:migrate 何も走ってないから、yamlがミスってても気づきにくいねｗ
> あとは .travis.yaml のほうに service: postgres 的なものが要るのかどうかがよくわかっていない。

db:createやmigrate自体が走ってないのでエラーも起きずミスに気づかなかったという問題も

**Comment by hfm** [comment]
CIが通って緑が表示されると、なんだかホッとするよねえ。

絶対に通るテストを書いてしまうことが未だにあるので、よっぽど注意深く見たり、
この変更の裏では何が起きるのだろう...と想像しなきゃいけないなあと痛感させられる。

**Comment by shimoju** [comment]
> CIが通って緑が表示されると、なんだかホッとするよねえ。

あの緑、ほっとしてしまいますね……！

おっくんから「図を使ってわかりやすくする（AAやcacooやkeynote）」とか
特にデータ処理であれば「このような結果になれば正しいです」という例があるとわかりやすくなる、
という話をいただきました
「こうしたい」「こうなると正しい」→「というわけでこのコードが本当にそうなってるか確かめてくれ」というような形がレビューの基本形なのかな

単純な文法ミスならエラーが出るし、コーディングスタイル・ルールならフォーマッターを使うとかRubocopなどのbotに任せるとかで負担は軽減できるけど、
意味的なエラー（絶対に通るテストを書いてしまうとか）は人間にしかわからないので、コード書いてる本人以上にレビュアー大事だなあ、と

**Comment by Asuforce** [comment]
CIの経験が無かったのもあってシグナルだけで判断してしまいましたね
経験が無いと想像もできないですね...

**Comment by shimoju** [comment]
## 毎日のふりかえり 6/15
- 今日やったこと
  - Ch2 #7 終了、Ch3 #8 の途中で終わった
- 明日やること
  - 引き続きCh3を進める、このペースだとCh4の途中か、ぎりぎり終わるくらい
  - Ch4はRubyについてなので、知ってることはさっとやって、今日出たブロックつきメソッドやProcなどよくわかんないとこを学習してみたりしたい
- スケジュール
  - みんなよりは遅れているが、予定通りには進んでいる
    - Ch2は午前中で終わっているので1日分でできている

### KPT
- 前日のTry「タイマー導入（ポモドーロもよさそう）、イヤホンしてみる」
  - イヤホンはダメだった（スピーカーで小さい音で流すのはいいが、イヤホンだと気になる）
  - 「きりのいいとこまで」は休憩に入りにくくなるのでよくない
  - タイマーは音がないのでうまく活用できなかった　スマホでバイブで鳴らすといいかも
- K：いろいろ試した
- P：休憩時間管理、集中力、定時が近づくと英語が記号にしか見えなくなる
- T：スマホでバイブで鳴らすアラームを導入

### その他

レビューに関してはブログ記事書きたいな〜〜

**Comment by shimoju** [comment]
夕会で出たRubyのブロックやProcをきちんと学習したい

りょうの作ったのがわかりやすかった
https://gist.github.com/ry023/41cb1af402978c01929723659a1acd3b

**Comment by shimoju** [comment]
本日のTry
- 時間を完全に区切る
- バイブで鳴るアラームの導入
  - https://itunes.apple.com/jp/app/baibuaramu-yinno-mingranaibaibudakeno/id949082325?mt=8

**Comment by shimoju** [comment]
間違えてcloseしてしまったのでreopen

**Comment by shimoju** [comment]
## 毎日のふりかえり 6/16
- 今日やったこと
  - Ch3 #8 終了したが、まだレビューしてもらっていない
- 明日やること
  - （今日できなかった）Ch4はRubyについてなので、知ってることはさっとやって、今日出たブロックつきメソッドやProcなどよくわかんないとこを学習してみたりしたい
- スケジュール
  - 今日でCh4に入れなかったのでやや遅れ始めたが、まだ焦るほどではない
  - レビューでほかの人を見ている感じだとCh4、5は自分はそこまでつらくなさそうな感じ
  - ただ、これからレビュー時間がどんどん長くなっていったり、随時差し込み作業は入ってくるので、夕会で出たように余裕を持ったスケジュールが大切

### KPT
- 本日のTry：時間を完全に区切る、バイブで鳴るアラームの導入
  - 強制的に区切るのは休憩がとりやすくなってよかった
  - サードパーティーのアラームアプリだとロック画面に残り時間表示とかができないので、無音ファイルを着信音として設定して純正アラームを使うほうがよさそう
  - 休憩後にアラームを忘れる事件
- K：自分だけの作業に閉じこもることなく、先の章でもわかることは教えあった
- P：レビューや差し込み作業を含めた、余裕を持ったスケジュールの構築
- T：無音ファイルを着信音として設定して純正アラームを使う

### その他

後ろを走っていると、そこわかるのに！でもまず自分のやらなきゃ…っていうもどかしさがある
（まあ今日は普通に教えていたんだけど）

**Comment by shimoju** [comment]
## 毎日のふりかえり 6/17
- 今日やったこと
  - Ch3、Ch4をレビューしてもらい完了
- 明日（来週）やること
  - Ch5をやっていく
  - 1習慣のふりかえりでTryが出ているので、実践する
- スケジュール
  - Ch5まで入れれば理想だったが、Ch4は終わらせられたので目標は達成

### KPT
- 「今週のふりかえり」で出たとおり
  - わからないことがあったとき、誰がくわしいのか、探す、スーパーバイザーに聞く
  - 完全じゃなくてもええやんって思う:ok_woman:
  - ガバッと見積もっていっぱい失敗しましょう

### その他

プライベートな用事（引っ越し）で疲れているところもあるが、
マルチタスクにならなきゃやっていけないので、どうにかバランスしていきたい

**Comment by shimoju** [comment]
Chapter 5、永遠を感じる

**Comment by shimoju** [comment]
## 毎日のふりかえり 6/20
- 今日やったこと
  - Ch5を完了、レビューはまだ
- 明日（来週）やること
  - レビューしてもらってCh6に入る
- スケジュール
  - レビューまではいけなかったが、Ch5を1日で終わらせることができた
  - 最後の方のチャプターに3日ずつかけても余裕が出るスケジュールになってきた
  - 引き続き、わかるところはスピーディにいきたい

### KPT
- K：体調がよくなかったが、休憩をこまめに入れて頑張った
- P：頑張ったけどだらだらした。思い切って仮眠をとるなどしてもよかった
- T：だめなときはYours仮眠を試してみる

### その他

家にベッドとカーテンがついたのでようやく人間らしい生活になってきた

**Comment by shimoju** [comment]
## 毎日のふりかえり 6/21
- 今日やったこと
  - Ch6の途中 前半で終わったので進みとしては遅かった
- 明日（来週）やること
  - Ch6完了が目標
- スケジュール
  - コーディング講座とエンジニア座学が挟まったらあっという間に終わってしまった
  - 2日で見積もっているので明日終われば問題ない

### KPT
- K：Travisセットアップなど、本筋以外のPRも出している
- P：タスクスイッチングがうまくできない、集中モードに入るまでの時間が長い
- T：タイマー利用がなあなあになっているので、時計に管理されてリズムを作る方法をしっかり試してみる

### その他

スリープから復帰せず「問題が発生したためコンピュータを再起動しました」
と言われて作業が一時中断した
カーネルパニックらしいです
https://support.apple.com/ja-jp/HT200553

**Comment by shimoju** [comment]
`rails console --sandbox`知らなかった…

**Comment by shimoju** [comment]
Tutorialの正規表現で`\A`と`\z`が使われてて気になった
https://www.railstutorial.org/book/modeling_users#table-valid_email_regex

正規表現によるバリデーションでは ^ と $ ではなく \A と \z を使おう | 徳丸浩の日記
http://blog.tokumaru.org/2014/03/z.html

> 正規表現によるバリデーション等で、完全一致を示す目的で ^ と $ を用いる方法が一般的ですが、正しくは \A と \z を用いる必要があります。Rubyの場合 ^ と $ を使って完全一致のバリデーションを行うと脆弱性が入りやすいワナとなります。
> メタ文字 ^ と $ は「行」の先頭と末尾を示す
> Rubyの正規表現機能は、デフォルトで複数行モードである
> 文字列のバリデーションなどに正規表現を用いる場合、^ と $ を使わずに、\A と \zを文字列の先頭・末尾を示すメタ文字として使用します。

ということらしい。なるほど〜

こちらも参考
Railsの正規表現でよく使われる \A \z って何？？ - Qiita
http://qiita.com/jnchito/items/ea7832df6f64a9034872

**Comment by shimoju** [comment]
## 毎日のふりかえり 6/22
- 今日やったこと
  - Ch6完了、レビューはまだ
- 明日（来週）やること
  - レビューしてもらってCh7に入る
- スケジュール
  - レビューまで終わらせたかったがそれは間に合わなかった
  - ただ、目標だったCh6を終わらせることはできた

### KPT
- K：終わらせる気持ち
- P：本筋のRails Tutorialをやっていくだけで時間が過ぎて、アウトプットや+αのことができていない
- T：少なくとも学んだことや気付きはIssueに明示的に書くようにはしているけど、もう一歩進みたい
  - 1日x分はRT以外のこと（アウトプットその他）をする、というx%ルールを設定するという方法
    - 気分転換にもなる
  - それできちんと終わるのか？問題

### その他

今日は[WEB DIRECTORS SESSION](http://pepabo.connpass.com/event/32336/)に行きます
友人も誘いました

**Comment by shimoju** [comment]
## 毎日のふりかえり 6/23（24日記入）
- 今日やったこと
  - Ch6をレビューしてもらって完了、Ch7前半で早退
- 明日（来週）やること
  - Ch7をやっていく
- スケジュール
  - 体調不良で早退してしまったので遅れが出てきた
  - 焦ると手につかなくなって英語も読めなくなるので、着実にやっていこう

### KPT
- 省略：6/24ふりかえりでまとめてやる

**Comment by shimoju** [comment]
## 毎日のふりかえり 6/24
- 今日やったこと
  - Ch7の8割程度までできた
- 明日（来週）やること
  - 午前中でCh7を終わらせ、Ch8に入る
- スケジュール
  - 昨日午後やっていれば終われた状態なので、進捗は悪くない

### KPT
- 来週のTRY（全員）
  - 自分用メモをブログに書く
  - #6th_engineers に「〜について調べてます」とか、進捗をどんどん書こう
  - レビュー依頼文に対するレビュー（コメント）をする
- 個人
  - P：見積もりが「がんばるぞ」になってしまう件
    - T：「2日で1チャプターを終わらせる」だけでなく、このチャプターで何を目的にするのか、スケジュールがある中で何を優先するか、まで考える

### 読書会
- 「コードに思いを込める」「思い」ってなんだろうなあと考えた
  - 本人が改善するなら、自然言語で説明して書き直す、というこの手法が使える
  - 本人じゃなくても、書いた人が近くにいるなら聞ける
  - じゃあいなかったら？（例えば退職していた場合）
- テストがあるとよくなる
  - テストはそのコードがどう動くべきかの期待が書かれているので、テストには思いがこめられていると言えるのでは

### その他

きんようび〜〜〜

**Comment by shimoju** [comment]
## 毎日のふりかえり 6/27
- 今日やったこと
  - Ch7完了、Ch8の3割程度までできた
- 明日（来週）やること
  - Ch8が終わればいいが、座学もあるし明後日の午前までかかっちゃうと思う
- スケジュール
  - 1チャプター2.5日くらいでやるとJSON API化をちょっとやれる余裕が出るので、いいペースでいきたいが…

### KPT

> - 今週のTRY
>   - 自分用メモをブログに書く
>   - #6th_engineers に「〜について調べてます」とか、進捗をどんどん書こう
>   - レビュー依頼文に対するレビュー（コメント）をする
- K：とても眠かったが、こまめに休憩を入れたりマッサージチェアも使って頑張った
- P：「進捗をどんどん書こう」ができなかった
- T：質問・疑問系だけでなく、進捗もどんどん報告することを意識する
  - A：少なくとも午前2回、午後2回の進捗報告を行う（休憩のタイミングがよいかな）

**Comment by shimoju** [comment]
## 毎日のふりかえり 6/28
- 今日やったこと
  - ぜんぜんだめだった
  - Ch8の半分まで
- 明日（来週）やること
  - 引き続きCh8
- スケジュール
  - じわじわと遅れが広がってきている
  - まだ火曜日なのでこのコンディションのまま週を終えるときついことになるので、早急に改善したい

### KPT
- K：「進捗をどんどん書こう」ができた
- P：
  - 集中力が0だった
    - チュートリアルがアップデートされた事件などのアクシデントはあったが、それにしても
  - 昨日はマッサージチェア休憩をしたが、今日は座学ありで時間が短かかったので頑張ろうとしてしまった
  - 進捗が体調に影響されすぎる
- T：
  - 時間がないときでもだめなときは休憩する勇気
  - 集中力強化のため、一番最初に試してダメだったイヤホンを再度試してみる
    - iPhone付属のイヤホンならオープン型で音が近すぎて集中してしまうのを軽減できそう（音漏れには注意）

### その他

進捗は悪かったが、座学のコードレビューについて（byあまこうさん）はとても学びが深かった
先輩たちも同じことを悩みながらレビューして/してもらっていることがわかって、
険しい道を進んでいこうという気持ちになった
がんばるぞ

**Comment by shimoju** [comment]
今日はよく眠れたし、iPhone付属イヤホンで聞いてみるTRYもいい感じ

**Comment by shimoju** [comment]
****

**Comment by shimoju** [comment]
また間違えてクローズしてしまった…！

## 毎日のふりかえり 6/29
- 今日やったこと
  - Ch8の8割完了
- 明日（来週）やること
  - Ch8を終了し、Ch9に入る
- スケジュール
  - 今日は集中力を取り戻した
  - 昨日の進捗が痛いが、やっていくだけ

### KPT
- K：iPhone付属のイヤホンを使うTRY、よかったので続ける
  - 周りの音もいい感じに聞こえて、音楽に気が行ってしまうのを避けられるし周りのことに気付ける
- P：やっぱり英語を読もうとしすぎる
- T：
  - 夕会で出た：昨日の座学に習ってプルリクを小さく分割してみよう
  - 後半の章になると変更点も多くなって、何をしたか把握が難しくなってくる
  - セクションごとや意味ごとに分割するとdiff少なくてレビューしやすそう
  - でも変更が次の変更に依存するので、レビューの仕方を相談必要

**Comment by shimoju** [comment]
## 毎日のふりかえり 6/30
- 今日やったこと
  - Ch8のエクササイズ2
- 明日（来週）やること
  - レビューしてもらいCh9に
- スケジュール
  - 火曜よりは断然集中できているが、進捗が遅い
  - メンバーの中でも遅れが広がってきた

### KPT
- K：iPhone付属のイヤホンを使うTRY継続
- P：やっぱりやっぱり英語を読もうとしすぎる
- T：
  - まず期日内に終わらせることを重視する
  - 夕会で質問できるし、その場で理解しきろうとしすぎない

### 読書会
- 1冊目『リーダブルコード』が終わり、2冊目『理論から学ぶデータベース実践入門』へ
- 最初からかなりごつい
- リレーショナルモデルの理論は全然知らなかったのでやっていくぞ

**Comment by shimoju** [comment]
## 毎日のふりかえり 7/1
- 今日やったこと
  - Ch8終了、Ch9半分ちょい
- 明日（来週）やること
  - Ch9を終わらせたい
- スケジュール
  - 今週はかなり苦しんだが、金曜で上向きに上がって終わることができた
  - 遅れを取り戻す…までいうと難しいが、JSON API化のさわりに入れるくらいのペースで、残り2週間やっていきたい

### KPT
- 来週のTRY（全員）
  - 30分わからなかったら聞く
  - 一番伝えたい内容はよく確認する
  - サブセクションでPRを作って完成したらレビューに出す

**Comment by shimoju** [comment]
## 毎日のふりかえり 7/4
- 今日やったこと
  - Ch9のエクササイズまで
- 明日（来週）やること
  - エクササイズを終わらせて、Ch10に入る
- スケジュール
  - 全体ミーティングがありCh9完了まではいかなかった

### KPT

> - 今週のTRY（全員）
>   - 30分わからなかったら聞く
>   - 一番伝えたい内容はよく確認する
>   - サブセクションでPRを作って完成したらレビューに出す

**Comment by shimoju** [comment]
## 毎日のふりかえり 7/5
- 今日やったこと
  - Ch9終了してCh10の最初まで
- 明日（来週）やること
  - Ch10の半分以上まで進める
- スケジュール
  - 最高とはいえないがペースは上向きになっているので、先週のようにならないように引き続き頑張りたい

### KPT

> - 今週のTRY（全員）
>   - 30分わからなかったら聞く
>   - 一番伝えたい内容はよく確認する
>   - サブセクションでPRを作って完成したらレビューに出す
- K：エクササイズの自由度が高くなってきたので、色々自分で考えながらやった
- P：難しく考えすぎた。きちんと問題文を読めば問題なかった
  - https://github.com/shimoju/rails-tutorial/pull/25#issuecomment-230224329
- T：エクササイズの問題文は、一見してわからなかったらきちんと訳して読み込む。勝手に考えすぎない

**Comment by shimoju** [comment]
## 毎日のふりかえり 7/6
- 今日やったこと
  - Ch10 section1終了、レビューはまだ
  - レビューで実際のメール送信を確認してもらいたかったので、10.3の本番環境用メール設定を先取りした
- 明日（来週）やること
  - Ch10を終わらせる
- スケジュール
  - 10.1だけで分量としては半分あり、10.3もできたので「半分以上まで進める」目標を達成できた
  - JSON API化の完成はほぼ無理だが、さわりには入れるようにこのままのペースで進めたい

### KPT

> - 今週のTRY（全員）
>   - 30分わからなかったら聞く
>   - 一番伝えたい内容はよく確認する
>   - サブセクションでPRを作って完成したらレビューに出す
- K：適宜コメントを書きながら、コードを理解することを意識した
- P：ペースが戻ったのに慣れてきたのか、集中力がちょっと途切れた
- T：ちょっと切れてきたな、というときにはきちんと休憩を取る、初心に戻ろう

**Comment by shimoju** [comment]
『プログラミングコンテスト攻略のためのアルゴリズムとデータ構造』
の読書会がはじまったぞ〜
難しいけど楽しそうなのでがんばるぞ〜

## 毎日のふりかえり 7/7
- 今日やったこと
  - Ch10.2終了、残りはエクササイズ
- 明日（来週）やること
  - 午前中にCh10を終わらせ、Ch11に入るくらいまではやりたい
  - 午後はDC見学
- スケジュール
  - 「ここまでいけたら理想だけどまあこんなもんかな〜」ぐらいのところに収まってしまう
  - バチっとしたい

### KPT

> - 今週のTRY（全員）
>   - 30分わからなかったら聞く
>   - 一番伝えたい内容はよく確認する
>   - サブセクションでPRを作って完成したらレビューに出す
- K：前日同様、適宜コメントを書きながら、コードを理解することを意識した
- P：特に難しいことは書かれていないのにコード量に圧倒された（Ch10.2のインテグレーションテスト）
- T：本番コードに比べれば全然行数は少ないので、長めのコードを読む練習と思う
  - 漫然と読まずにまずここ、次ここ、と区切って集中する

**Comment by shimoju** [comment]
データセンターすごかった（小学生並の感想）

## 毎日のふりかえり 7/8
- 今日やったこと
  - Ch10エクササイズ終了したが、Extraをやりたいのでまだレビュー出してない
- 明日（来週）やること
  - Extraをさくっと終わらせてレビュー、Ch11の半分までを目標
- スケジュール
  - 午前中にふりかえり会もやったので、ぎりぎり終われるかなという状況

### KPT

> - 来週のTRY（全員）
>   - 本日のトピックを共有する
>   - 読書会をページ決めずに時間区切りにする（20分）

**Comment by shimoju** [comment]
## 毎日のふりかえり 7/11
- 今日やったこと
  - エクササイズExtra credit終了してCh10完了
  - Chapter11の1まで
- 明日（来週）やること
  - Chapter11のエクササイズ前までを目標
- スケジュール
  - Ch11の半分までが目標………うっ
  - Extraで考えすぎてしまった、時間がないことを考慮すべきだった

### KPT

> - 今週のTRY（全員）
>   - 本日のトピックを共有する
>   - 読書会をページ決めずに時間区切りにする（20分）
- K：今日は見当たらない…
- P：考えすぎて頭がぐちゃぐちゃになった
- T：「30分わからなかったら聞く」というTryを思い出そう
  - プルリクはせっかくコードが出せるんだから、いつまでも考えすぎず「こう考えたんだけどどうですか」とレビューを仰ごう

**Comment by shimoju** [comment]
Herokuでデータベースをリセットしたいときは

```
heroku pg:reset DATABASE
```

でできる
（rakeコマンドの`rake db:migrate:reset`や`db:drop`ではできない）

http://qiita.com/quattro_4/items/a2eb3618207e21ca00d3

**Comment by shimoju** [comment]
## 毎日のふりかえり 7/12
- 今日やったこと
  - Chapter11.2終了、11.3の途中
- 明日（来週）やること
  - Ch11終了してCh12に入る
- スケジュール
  - 残り3日でCh11半分とCh12
  - 水曜は座学等なし、木曜は座学あり、金曜はふりかえり
  - 明日でCh12に入らないと相当厳しい
    - 明日でCh12行けなかったり体調不良などで見込みが厳しい場合、相談

### KPT

> - 今週のTRY（全員）
>   - 本日のトピックを共有する
>   - 読書会をページ決めずに時間区切りにする（20分）
- K：レビューでコメントをいっぱいした
- P：もっとスピードアップしなければ
- T：Slackなど、目を離す時間を減らす
  - あと風邪を直す……
  - あとどんなアクションがあるだろうか

**Comment by shimoju** [comment]
## 毎日のふりかえり 7/13
- 今日やったこと
  - Chapter11終了、Ch12に入った
- 明日（来週）やること
  - Ch12後半〜8割程度終わらせたい
- スケジュール
  - 今日でCh11終われた…！
  - 間に合いそうな見込みが出てきたので、残り2日やっていくぞ

**Comment by shimoju** [comment]
## 毎日のふりかえり 7/14
- 今日やったこと
  - Ch12.2まで終了
- 明日（来週）やること
  - Ch12.3とエクササイズでチュートリアル終わり
  - JSONを少しは触りたい…！
- スケジュール
  - 12.2まで終わり、十分明日で完了できる見込みになった
  - 気を引き締めて明日で終わらせるぞ！

**Comment by hfm** [comment]
なつかしい（通知来た

**Comment by shimoju** [comment]
issueの棚卸ししてました…！（自分もなつかしいです）

**Comment by Asuforce** [comment]
記念パピコ（通知きた
